import type { PrintConfig } from "@/types/modal";

export const receiptPrintConfig: PrintConfig = {
  title: {
    vi: "DANH SÁCH PHIẾU THU",
    en: "RECEIPT LIST",
    ko: "영수증 목록",
  },
  columns: {
    receiptNo: { vi: "Số chứng từ", en: "Receipt No", ko: "증빙번호" },
    transactionDate: { vi: "Ngày giao dịch", en: "Transaction Date", ko: "거래일" },
    amount: { vi: "Số tiền", en: "Amount", ko: "금액" },
    description1: { vi: "Mô tả 1", en: "Description 1", ko: "설명1" },
    description2: { vi: "Mô tả 2", en: "Description 2", ko: "설명2" },
    receiverName: { vi: "Người nhận tiền", en: "Receiver", ko: "수령인" },
    modifiedDate: { vi: "Ngày sửa đổi", en: "Modified Date", ko: "수정일" },
    isLocked: { vi: "Đã khóa", en: "Locked", ko: "잠금" },
    email: { vi: "Email", en: "Email", ko: "이메일" },
    attachment: { vi: "File đính kèm", en: "Attachment", ko: "첨부파일" },
    createdBy: { vi: "Người tạo", en: "Created By", ko: "생성자" },
    currentEditor: { vi: "Người sửa đổi hiện tại", en: "Current Editor", ko: "최종수정자" },
    costCenter1: { vi: "Đối tượng tập hợp chi phí 1", en: "Cost Center 1", ko: "비용집계대상1" },
    costCenter2: { vi: "Đối tượng tập hợp chi phí 2", en: "Cost Center 2", ko: "비용집계대상2" },
    debit: { vi: "Nợ", en: "Debit", ko: "차변" },
    debitAccountName: { vi: "Tên tài khoản nợ", en: "Debit Account Name", ko: "차변계정명" },
    credit: { vi: "Có", en: "Credit", ko: "대변" },
    creditAccountName: { vi: "Tên tài khoản có", en: "Credit Account Name", ko: "대변계정명" },
    amountSecond: { vi: "Số tiền (2)", en: "Amount (2)", ko: "금액2" },
    fcAmount: { vi: "FC Số tiền", en: "FC Amount", ko: "외화금액" },
    country: { vi: "Quốc gia", en: "Country", ko: "국가" },
    customerCode: { vi: "Mã khách hàng", en: "Customer Code", ko: "고객코드" },
    customerName: { vi: "Tên khách hàng", en: "Customer Name", ko: "고객명" },
    bankName: { vi: "Tên ngân hàng", en: "Bank Name", ko: "은행명" },
    manageCode: { vi: "Mã số quản lý", en: "Manage Code", ko: "관리코드" },
    manageCode2: { vi: "Mã số quản lý 2", en: "Manage Code 2", ko: "관리코드2" },
    note1: { vi: "Quản lý ghi chú 1", en: "Note 1", ko: "비고1" },
    note2: { vi: "Quản lý ghi chú 2", en: "Note 2", ko: "비고2" },
    inventory: { vi: "Hàng tồn kho", en: "Inventory", ko: "재고" },
  },
  translations: {
    vi: {
      title: "DANH SÁCH PHIẾU THU",
      printDate: "Ngày in",
      columns: { stt: "STT" },
      footer: {
        preparedBy: "Người lập biểu",
        accountant: "Kế toán trưởng",
        director: "Giám đốc",
        signature: "(Ký họ tên)",
        date: "Ngày ... tháng ... năm ...",
      },
      summary: "Tổng cộng có {count} phiếu thu",
    },
    en: {
      title: "RECEIPT LIST",
      printDate: "Print Date",
      columns: { stt: "No." },
      footer: {
        preparedBy: "Prepared by",
        accountant: "Chief Accountant",
        director: "Director",
        signature: "(Signature)",
        date: "Date ... Month ... Year ...",
      },
      summary: "Total {count} receipts",
    },
    ko: {
      title: "영수증 목록",
      printDate: "인쇄일",
      columns: { stt: "번호" },
      footer: {
        preparedBy: "작성자",
        accountant: "회계담당",
        director: "대표",
        signature: "(서명)",
        date: "...년 ...월 ...일",
      },
      summary: "총 {count}건 영수증",
    },
  },
};
